theme: null
url: "https://nottepad.com"
plugins:
  - jekyll-sitemap
languages:
  en: "/"
  pt-br: "/pt-br/"
  es: "/es/"
  ja: "/ja/"
  ru: "/ru/"
  zh-cn: "/zh-cn/"
  it: "/it/"
  de: "/de/"
  ko: "/ko/"
  fr: "/fr/"